//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace.ServicoDeAutenticacao {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoAutenticar", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoAutenticar : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginOuSenhaInvalidos = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ResetDeDadosPendente = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoNotificarLimpezaDadosLocais", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoNotificarLimpezaDadosLocais : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroInesperado = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoObterUrlVersao", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoObterUrlVersao : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoObterVersaoAndroid", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoObterVersaoAndroid : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 0,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parametrizacao", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.D" +
        "ados")]
    public partial class Parametrizacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescricaoField;
        
        private long IdField;
        
        private string ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorField, value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoListarParametrizacoes", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoListarParametrizacoes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcessoNegado = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.D" +
        "ados")]
    public partial class Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long IdField;
        
        private string LoginField;
        
        private string NomeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoListarUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoListarUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcessoNegado = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoObterUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoObterUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcessoNegado = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoAlterarUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoAlterarUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcessoNegado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TamanhoNomeInvalido = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsuarioExistente = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NomeObrigatorio = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoAlterarSenha", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoAlterarSenha : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcessoNegado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TamanhoNomeInvalido = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsuarioExistente = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NomeObrigatorio = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoCriarUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoCriarUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcessoNegado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TamanhoLoginInvalido = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TamanhoNomeInvalido = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsuarioExistente = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NomeObrigatorio = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginObrigatorio = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SenhaObrigatoria = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoBloquearUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoBloquearUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AcessoNegado = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FalhaAoObterIdDoUsuarioPorReferenciaDeAutenticacao", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
        "alhas")]
    public enum FalhaAoObterIdDoUsuarioPorReferenciaDeAutenticacao : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HistoricoDeAutenticacaoInexistente = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDesconhecido = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoDeAutenticacao.ServicoDeAutenticacao")]
    public interface ServicoDeAutenticacao {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/Autenticar", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/AutenticarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoAutenticar), Action="http://tempuri.org/ServicoDeAutenticacao/AutenticarFalhaAoAutenticarFault", Name="FalhaAoAutenticar", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginAutenticar(string login, string senha, System.AsyncCallback callback, object asyncState);
        
        System.Guid EndAutenticar(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/AutenticarComOrigem", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/AutenticarComOrigemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoAutenticar), Action="http://tempuri.org/ServicoDeAutenticacao/AutenticarComOrigemFalhaAoAutenticarFaul" +
            "t", Name="FalhaAoAutenticar", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginAutenticarComOrigem(string login, string senha, string origem, System.AsyncCallback callback, object asyncState);
        
        System.Guid EndAutenticarComOrigem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/NotificaLimpezaDadosLocais", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/NotificaLimpezaDadosLocaisResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoNotificarLimpezaDadosLocais), Action="http://tempuri.org/ServicoDeAutenticacao/NotificaLimpezaDadosLocaisFalhaAoNotific" +
            "arLimpezaDadosLocaisFault", Name="FalhaAoNotificarLimpezaDadosLocais", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginNotificaLimpezaDadosLocais(string login, System.AsyncCallback callback, object asyncState);
        
        void EndNotificaLimpezaDadosLocais(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/ObterUrlVersao", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/ObterUrlVersaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoObterUrlVersao), Action="http://tempuri.org/ServicoDeAutenticacao/ObterUrlVersaoFalhaAoObterUrlVersaoFault" +
            "", Name="FalhaAoObterUrlVersao", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginObterUrlVersao(System.AsyncCallback callback, object asyncState);
        
        string EndObterUrlVersao(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/ObterVersaoAndroid", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/ObterVersaoAndroidResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoObterVersaoAndroid), Action="http://tempuri.org/ServicoDeAutenticacao/ObterVersaoAndroidFalhaAoObterVersaoAndr" +
            "oidFault", Name="FalhaAoObterVersaoAndroid", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginObterVersaoAndroid(System.AsyncCallback callback, object asyncState);
        
        string EndObterVersaoAndroid(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/ListarParametrizacoes", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/ListarParametrizacoesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoListarParametrizacoes), Action="http://tempuri.org/ServicoDeAutenticacao/ListarParametrizacoesFalhaAoListarParame" +
            "trizacoesFault", Name="FalhaAoListarParametrizacoes", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginListarParametrizacoes(System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Parametrizacao> EndListarParametrizacoes(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/ListarUsuarios", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/ListarUsuariosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoListarUsuario), Action="http://tempuri.org/ServicoDeAutenticacao/ListarUsuariosFalhaAoListarUsuarioFault", Name="FalhaAoListarUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginListarUsuarios(System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Usuario> EndListarUsuarios(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/ObterUsuario", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/ObterUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoObterUsuario), Action="http://tempuri.org/ServicoDeAutenticacao/ObterUsuarioFalhaAoObterUsuarioFault", Name="FalhaAoObterUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginObterUsuario(long id, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState);
        
        Marketplace.ServicoDeAutenticacao.Usuario EndObterUsuario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/AlterarUsuario", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/AlterarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoAlterarUsuario), Action="http://tempuri.org/ServicoDeAutenticacao/AlterarUsuarioFalhaAoAlterarUsuarioFault" +
            "", Name="FalhaAoAlterarUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginAlterarUsuario(long id, string nome, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState);
        
        void EndAlterarUsuario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/AlterarSenha", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/AlterarSenhaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoAlterarSenha), Action="http://tempuri.org/ServicoDeAutenticacao/AlterarSenhaFalhaAoAlterarSenhaFault", Name="FalhaAoAlterarSenha", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginAlterarSenha(string senha, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState);
        
        void EndAlterarSenha(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/CriarUsuario", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/CriarUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoCriarUsuario), Action="http://tempuri.org/ServicoDeAutenticacao/CriarUsuarioFalhaAoCriarUsuarioFault", Name="FalhaAoCriarUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginCriarUsuario(string nome, string login, string senha, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState);
        
        Marketplace.ServicoDeAutenticacao.Usuario EndCriarUsuario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/BloquearUsuario", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/BloquearUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoBloquearUsuario), Action="http://tempuri.org/ServicoDeAutenticacao/BloquearUsuarioFalhaAoBloquearUsuarioFau" +
            "lt", Name="FalhaAoBloquearUsuario", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginBloquearUsuario(long id, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState);
        
        void EndBloquearUsuario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ServicoDeAutenticacao/ObterIdDoUsuarioPorReferenciaDeAutentica" +
            "cao", ReplyAction="http://tempuri.org/ServicoDeAutenticacao/ObterIdDoUsuarioPorReferenciaDeAutentica" +
            "caoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Marketplace.ServicoDeAutenticacao.FalhaAoObterIdDoUsuarioPorReferenciaDeAutenticacao), Action="http://tempuri.org/ServicoDeAutenticacao/ObterIdDoUsuarioPorReferenciaDeAutentica" +
            "caoFalhaAoObterIdDoUsuarioPorReferenciaDeAutenticacaoFault", Name="FalhaAoObterIdDoUsuarioPorReferenciaDeAutenticacao", Namespace="http://schemas.datacontract.org/2004/07/Pharmalink.ServicoDistribuido.Seguranca.F" +
            "alhas")]
        System.IAsyncResult BeginObterIdDoUsuarioPorReferenciaDeAutenticacao(System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState);
        
        long EndObterIdDoUsuarioPorReferenciaDeAutenticacao(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoDeAutenticacaoChannel : Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AutenticarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Guid Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticarComOrigemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AutenticarComOrigemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Guid Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Guid)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObterUrlVersaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObterUrlVersaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObterVersaoAndroidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObterVersaoAndroidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarParametrizacoesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarParametrizacoesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Parametrizacao> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Parametrizacao>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Usuario> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Usuario>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObterUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObterUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Marketplace.ServicoDeAutenticacao.Usuario Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Marketplace.ServicoDeAutenticacao.Usuario)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CriarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CriarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Marketplace.ServicoDeAutenticacao.Usuario Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Marketplace.ServicoDeAutenticacao.Usuario)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObterIdDoUsuarioPorReferenciaDeAutenticacaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObterIdDoUsuarioPorReferenciaDeAutenticacaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public long Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoDeAutenticacaoClient : System.ServiceModel.ClientBase<Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao>, Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao {
        
        private BeginOperationDelegate onBeginAutenticarDelegate;
        
        private EndOperationDelegate onEndAutenticarDelegate;
        
        private System.Threading.SendOrPostCallback onAutenticarCompletedDelegate;
        
        private BeginOperationDelegate onBeginAutenticarComOrigemDelegate;
        
        private EndOperationDelegate onEndAutenticarComOrigemDelegate;
        
        private System.Threading.SendOrPostCallback onAutenticarComOrigemCompletedDelegate;
        
        private BeginOperationDelegate onBeginNotificaLimpezaDadosLocaisDelegate;
        
        private EndOperationDelegate onEndNotificaLimpezaDadosLocaisDelegate;
        
        private System.Threading.SendOrPostCallback onNotificaLimpezaDadosLocaisCompletedDelegate;
        
        private BeginOperationDelegate onBeginObterUrlVersaoDelegate;
        
        private EndOperationDelegate onEndObterUrlVersaoDelegate;
        
        private System.Threading.SendOrPostCallback onObterUrlVersaoCompletedDelegate;
        
        private BeginOperationDelegate onBeginObterVersaoAndroidDelegate;
        
        private EndOperationDelegate onEndObterVersaoAndroidDelegate;
        
        private System.Threading.SendOrPostCallback onObterVersaoAndroidCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarParametrizacoesDelegate;
        
        private EndOperationDelegate onEndListarParametrizacoesDelegate;
        
        private System.Threading.SendOrPostCallback onListarParametrizacoesCompletedDelegate;
        
        private BeginOperationDelegate onBeginListarUsuariosDelegate;
        
        private EndOperationDelegate onEndListarUsuariosDelegate;
        
        private System.Threading.SendOrPostCallback onListarUsuariosCompletedDelegate;
        
        private BeginOperationDelegate onBeginObterUsuarioDelegate;
        
        private EndOperationDelegate onEndObterUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onObterUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginAlterarUsuarioDelegate;
        
        private EndOperationDelegate onEndAlterarUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onAlterarUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginAlterarSenhaDelegate;
        
        private EndOperationDelegate onEndAlterarSenhaDelegate;
        
        private System.Threading.SendOrPostCallback onAlterarSenhaCompletedDelegate;
        
        private BeginOperationDelegate onBeginCriarUsuarioDelegate;
        
        private EndOperationDelegate onEndCriarUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onCriarUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginBloquearUsuarioDelegate;
        
        private EndOperationDelegate onEndBloquearUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onBloquearUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginObterIdDoUsuarioPorReferenciaDeAutenticacaoDelegate;
        
        private EndOperationDelegate onEndObterIdDoUsuarioPorReferenciaDeAutenticacaoDelegate;
        
        private System.Threading.SendOrPostCallback onObterIdDoUsuarioPorReferenciaDeAutenticacaoCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ServicoDeAutenticacaoClient() : 
                base(ServicoDeAutenticacaoClient.GetDefaultBinding(), ServicoDeAutenticacaoClient.GetDefaultEndpointAddress()) {
        }
        
        public ServicoDeAutenticacaoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicoDeAutenticacaoClient.GetBindingForEndpoint(endpointConfiguration), ServicoDeAutenticacaoClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public ServicoDeAutenticacaoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicoDeAutenticacaoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public ServicoDeAutenticacaoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicoDeAutenticacaoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public ServicoDeAutenticacaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<AutenticarCompletedEventArgs> AutenticarCompleted;
        
        public event System.EventHandler<AutenticarComOrigemCompletedEventArgs> AutenticarComOrigemCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> NotificaLimpezaDadosLocaisCompleted;
        
        public event System.EventHandler<ObterUrlVersaoCompletedEventArgs> ObterUrlVersaoCompleted;
        
        public event System.EventHandler<ObterVersaoAndroidCompletedEventArgs> ObterVersaoAndroidCompleted;
        
        public event System.EventHandler<ListarParametrizacoesCompletedEventArgs> ListarParametrizacoesCompleted;
        
        public event System.EventHandler<ListarUsuariosCompletedEventArgs> ListarUsuariosCompleted;
        
        public event System.EventHandler<ObterUsuarioCompletedEventArgs> ObterUsuarioCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AlterarUsuarioCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AlterarSenhaCompleted;
        
        public event System.EventHandler<CriarUsuarioCompletedEventArgs> CriarUsuarioCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> BloquearUsuarioCompleted;
        
        public event System.EventHandler<ObterIdDoUsuarioPorReferenciaDeAutenticacaoCompletedEventArgs> ObterIdDoUsuarioPorReferenciaDeAutenticacaoCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginAutenticar(string login, string senha, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAutenticar(login, senha, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Guid Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndAutenticar(System.IAsyncResult result) {
            return base.Channel.EndAutenticar(result);
        }
        
        private System.IAsyncResult OnBeginAutenticar(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginAutenticar(login, senha, callback, asyncState);
        }
        
        private object[] OnEndAutenticar(System.IAsyncResult result) {
            System.Guid retVal = ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndAutenticar(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAutenticarCompleted(object state) {
            if ((this.AutenticarCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AutenticarCompleted(this, new AutenticarCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AutenticarAsync(string login, string senha) {
            this.AutenticarAsync(login, senha, null);
        }
        
        public void AutenticarAsync(string login, string senha, object userState) {
            if ((this.onBeginAutenticarDelegate == null)) {
                this.onBeginAutenticarDelegate = new BeginOperationDelegate(this.OnBeginAutenticar);
            }
            if ((this.onEndAutenticarDelegate == null)) {
                this.onEndAutenticarDelegate = new EndOperationDelegate(this.OnEndAutenticar);
            }
            if ((this.onAutenticarCompletedDelegate == null)) {
                this.onAutenticarCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAutenticarCompleted);
            }
            base.InvokeAsync(this.onBeginAutenticarDelegate, new object[] {
                        login,
                        senha}, this.onEndAutenticarDelegate, this.onAutenticarCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginAutenticarComOrigem(string login, string senha, string origem, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAutenticarComOrigem(login, senha, origem, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Guid Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndAutenticarComOrigem(System.IAsyncResult result) {
            return base.Channel.EndAutenticarComOrigem(result);
        }
        
        private System.IAsyncResult OnBeginAutenticarComOrigem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string senha = ((string)(inValues[1]));
            string origem = ((string)(inValues[2]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginAutenticarComOrigem(login, senha, origem, callback, asyncState);
        }
        
        private object[] OnEndAutenticarComOrigem(System.IAsyncResult result) {
            System.Guid retVal = ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndAutenticarComOrigem(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAutenticarComOrigemCompleted(object state) {
            if ((this.AutenticarComOrigemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AutenticarComOrigemCompleted(this, new AutenticarComOrigemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AutenticarComOrigemAsync(string login, string senha, string origem) {
            this.AutenticarComOrigemAsync(login, senha, origem, null);
        }
        
        public void AutenticarComOrigemAsync(string login, string senha, string origem, object userState) {
            if ((this.onBeginAutenticarComOrigemDelegate == null)) {
                this.onBeginAutenticarComOrigemDelegate = new BeginOperationDelegate(this.OnBeginAutenticarComOrigem);
            }
            if ((this.onEndAutenticarComOrigemDelegate == null)) {
                this.onEndAutenticarComOrigemDelegate = new EndOperationDelegate(this.OnEndAutenticarComOrigem);
            }
            if ((this.onAutenticarComOrigemCompletedDelegate == null)) {
                this.onAutenticarComOrigemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAutenticarComOrigemCompleted);
            }
            base.InvokeAsync(this.onBeginAutenticarComOrigemDelegate, new object[] {
                        login,
                        senha,
                        origem}, this.onEndAutenticarComOrigemDelegate, this.onAutenticarComOrigemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginNotificaLimpezaDadosLocais(string login, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginNotificaLimpezaDadosLocais(login, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndNotificaLimpezaDadosLocais(System.IAsyncResult result) {
            base.Channel.EndNotificaLimpezaDadosLocais(result);
        }
        
        private System.IAsyncResult OnBeginNotificaLimpezaDadosLocais(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginNotificaLimpezaDadosLocais(login, callback, asyncState);
        }
        
        private object[] OnEndNotificaLimpezaDadosLocais(System.IAsyncResult result) {
            ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndNotificaLimpezaDadosLocais(result);
            return null;
        }
        
        private void OnNotificaLimpezaDadosLocaisCompleted(object state) {
            if ((this.NotificaLimpezaDadosLocaisCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.NotificaLimpezaDadosLocaisCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void NotificaLimpezaDadosLocaisAsync(string login) {
            this.NotificaLimpezaDadosLocaisAsync(login, null);
        }
        
        public void NotificaLimpezaDadosLocaisAsync(string login, object userState) {
            if ((this.onBeginNotificaLimpezaDadosLocaisDelegate == null)) {
                this.onBeginNotificaLimpezaDadosLocaisDelegate = new BeginOperationDelegate(this.OnBeginNotificaLimpezaDadosLocais);
            }
            if ((this.onEndNotificaLimpezaDadosLocaisDelegate == null)) {
                this.onEndNotificaLimpezaDadosLocaisDelegate = new EndOperationDelegate(this.OnEndNotificaLimpezaDadosLocais);
            }
            if ((this.onNotificaLimpezaDadosLocaisCompletedDelegate == null)) {
                this.onNotificaLimpezaDadosLocaisCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnNotificaLimpezaDadosLocaisCompleted);
            }
            base.InvokeAsync(this.onBeginNotificaLimpezaDadosLocaisDelegate, new object[] {
                        login}, this.onEndNotificaLimpezaDadosLocaisDelegate, this.onNotificaLimpezaDadosLocaisCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginObterUrlVersao(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObterUrlVersao(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndObterUrlVersao(System.IAsyncResult result) {
            return base.Channel.EndObterUrlVersao(result);
        }
        
        private System.IAsyncResult OnBeginObterUrlVersao(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginObterUrlVersao(callback, asyncState);
        }
        
        private object[] OnEndObterUrlVersao(System.IAsyncResult result) {
            string retVal = ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndObterUrlVersao(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObterUrlVersaoCompleted(object state) {
            if ((this.ObterUrlVersaoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObterUrlVersaoCompleted(this, new ObterUrlVersaoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObterUrlVersaoAsync() {
            this.ObterUrlVersaoAsync(null);
        }
        
        public void ObterUrlVersaoAsync(object userState) {
            if ((this.onBeginObterUrlVersaoDelegate == null)) {
                this.onBeginObterUrlVersaoDelegate = new BeginOperationDelegate(this.OnBeginObterUrlVersao);
            }
            if ((this.onEndObterUrlVersaoDelegate == null)) {
                this.onEndObterUrlVersaoDelegate = new EndOperationDelegate(this.OnEndObterUrlVersao);
            }
            if ((this.onObterUrlVersaoCompletedDelegate == null)) {
                this.onObterUrlVersaoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObterUrlVersaoCompleted);
            }
            base.InvokeAsync(this.onBeginObterUrlVersaoDelegate, null, this.onEndObterUrlVersaoDelegate, this.onObterUrlVersaoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginObterVersaoAndroid(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObterVersaoAndroid(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndObterVersaoAndroid(System.IAsyncResult result) {
            return base.Channel.EndObterVersaoAndroid(result);
        }
        
        private System.IAsyncResult OnBeginObterVersaoAndroid(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginObterVersaoAndroid(callback, asyncState);
        }
        
        private object[] OnEndObterVersaoAndroid(System.IAsyncResult result) {
            string retVal = ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndObterVersaoAndroid(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObterVersaoAndroidCompleted(object state) {
            if ((this.ObterVersaoAndroidCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObterVersaoAndroidCompleted(this, new ObterVersaoAndroidCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObterVersaoAndroidAsync() {
            this.ObterVersaoAndroidAsync(null);
        }
        
        public void ObterVersaoAndroidAsync(object userState) {
            if ((this.onBeginObterVersaoAndroidDelegate == null)) {
                this.onBeginObterVersaoAndroidDelegate = new BeginOperationDelegate(this.OnBeginObterVersaoAndroid);
            }
            if ((this.onEndObterVersaoAndroidDelegate == null)) {
                this.onEndObterVersaoAndroidDelegate = new EndOperationDelegate(this.OnEndObterVersaoAndroid);
            }
            if ((this.onObterVersaoAndroidCompletedDelegate == null)) {
                this.onObterVersaoAndroidCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObterVersaoAndroidCompleted);
            }
            base.InvokeAsync(this.onBeginObterVersaoAndroidDelegate, null, this.onEndObterVersaoAndroidDelegate, this.onObterVersaoAndroidCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginListarParametrizacoes(System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarParametrizacoes(referenciaDeAutenticacao, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Parametrizacao> Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndListarParametrizacoes(System.IAsyncResult result) {
            return base.Channel.EndListarParametrizacoes(result);
        }
        
        private System.IAsyncResult OnBeginListarParametrizacoes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid referenciaDeAutenticacao = ((System.Guid)(inValues[0]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginListarParametrizacoes(referenciaDeAutenticacao, callback, asyncState);
        }
        
        private object[] OnEndListarParametrizacoes(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Parametrizacao> retVal = ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndListarParametrizacoes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarParametrizacoesCompleted(object state) {
            if ((this.ListarParametrizacoesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarParametrizacoesCompleted(this, new ListarParametrizacoesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarParametrizacoesAsync(System.Guid referenciaDeAutenticacao) {
            this.ListarParametrizacoesAsync(referenciaDeAutenticacao, null);
        }
        
        public void ListarParametrizacoesAsync(System.Guid referenciaDeAutenticacao, object userState) {
            if ((this.onBeginListarParametrizacoesDelegate == null)) {
                this.onBeginListarParametrizacoesDelegate = new BeginOperationDelegate(this.OnBeginListarParametrizacoes);
            }
            if ((this.onEndListarParametrizacoesDelegate == null)) {
                this.onEndListarParametrizacoesDelegate = new EndOperationDelegate(this.OnEndListarParametrizacoes);
            }
            if ((this.onListarParametrizacoesCompletedDelegate == null)) {
                this.onListarParametrizacoesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarParametrizacoesCompleted);
            }
            base.InvokeAsync(this.onBeginListarParametrizacoesDelegate, new object[] {
                        referenciaDeAutenticacao}, this.onEndListarParametrizacoesDelegate, this.onListarParametrizacoesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginListarUsuarios(System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListarUsuarios(referenciaDeAutenticacao, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Usuario> Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndListarUsuarios(System.IAsyncResult result) {
            return base.Channel.EndListarUsuarios(result);
        }
        
        private System.IAsyncResult OnBeginListarUsuarios(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid referenciaDeAutenticacao = ((System.Guid)(inValues[0]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginListarUsuarios(referenciaDeAutenticacao, callback, asyncState);
        }
        
        private object[] OnEndListarUsuarios(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Usuario> retVal = ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndListarUsuarios(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListarUsuariosCompleted(object state) {
            if ((this.ListarUsuariosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListarUsuariosCompleted(this, new ListarUsuariosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListarUsuariosAsync(System.Guid referenciaDeAutenticacao) {
            this.ListarUsuariosAsync(referenciaDeAutenticacao, null);
        }
        
        public void ListarUsuariosAsync(System.Guid referenciaDeAutenticacao, object userState) {
            if ((this.onBeginListarUsuariosDelegate == null)) {
                this.onBeginListarUsuariosDelegate = new BeginOperationDelegate(this.OnBeginListarUsuarios);
            }
            if ((this.onEndListarUsuariosDelegate == null)) {
                this.onEndListarUsuariosDelegate = new EndOperationDelegate(this.OnEndListarUsuarios);
            }
            if ((this.onListarUsuariosCompletedDelegate == null)) {
                this.onListarUsuariosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarUsuariosCompleted);
            }
            base.InvokeAsync(this.onBeginListarUsuariosDelegate, new object[] {
                        referenciaDeAutenticacao}, this.onEndListarUsuariosDelegate, this.onListarUsuariosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginObterUsuario(long id, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObterUsuario(id, referenciaDeAutenticacao, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marketplace.ServicoDeAutenticacao.Usuario Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndObterUsuario(System.IAsyncResult result) {
            return base.Channel.EndObterUsuario(result);
        }
        
        private System.IAsyncResult OnBeginObterUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            long id = ((long)(inValues[0]));
            System.Guid referenciaDeAutenticacao = ((System.Guid)(inValues[1]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginObterUsuario(id, referenciaDeAutenticacao, callback, asyncState);
        }
        
        private object[] OnEndObterUsuario(System.IAsyncResult result) {
            Marketplace.ServicoDeAutenticacao.Usuario retVal = ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndObterUsuario(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObterUsuarioCompleted(object state) {
            if ((this.ObterUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObterUsuarioCompleted(this, new ObterUsuarioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObterUsuarioAsync(long id, System.Guid referenciaDeAutenticacao) {
            this.ObterUsuarioAsync(id, referenciaDeAutenticacao, null);
        }
        
        public void ObterUsuarioAsync(long id, System.Guid referenciaDeAutenticacao, object userState) {
            if ((this.onBeginObterUsuarioDelegate == null)) {
                this.onBeginObterUsuarioDelegate = new BeginOperationDelegate(this.OnBeginObterUsuario);
            }
            if ((this.onEndObterUsuarioDelegate == null)) {
                this.onEndObterUsuarioDelegate = new EndOperationDelegate(this.OnEndObterUsuario);
            }
            if ((this.onObterUsuarioCompletedDelegate == null)) {
                this.onObterUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObterUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginObterUsuarioDelegate, new object[] {
                        id,
                        referenciaDeAutenticacao}, this.onEndObterUsuarioDelegate, this.onObterUsuarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginAlterarUsuario(long id, string nome, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAlterarUsuario(id, nome, referenciaDeAutenticacao, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndAlterarUsuario(System.IAsyncResult result) {
            base.Channel.EndAlterarUsuario(result);
        }
        
        private System.IAsyncResult OnBeginAlterarUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            long id = ((long)(inValues[0]));
            string nome = ((string)(inValues[1]));
            System.Guid referenciaDeAutenticacao = ((System.Guid)(inValues[2]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginAlterarUsuario(id, nome, referenciaDeAutenticacao, callback, asyncState);
        }
        
        private object[] OnEndAlterarUsuario(System.IAsyncResult result) {
            ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndAlterarUsuario(result);
            return null;
        }
        
        private void OnAlterarUsuarioCompleted(object state) {
            if ((this.AlterarUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AlterarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AlterarUsuarioAsync(long id, string nome, System.Guid referenciaDeAutenticacao) {
            this.AlterarUsuarioAsync(id, nome, referenciaDeAutenticacao, null);
        }
        
        public void AlterarUsuarioAsync(long id, string nome, System.Guid referenciaDeAutenticacao, object userState) {
            if ((this.onBeginAlterarUsuarioDelegate == null)) {
                this.onBeginAlterarUsuarioDelegate = new BeginOperationDelegate(this.OnBeginAlterarUsuario);
            }
            if ((this.onEndAlterarUsuarioDelegate == null)) {
                this.onEndAlterarUsuarioDelegate = new EndOperationDelegate(this.OnEndAlterarUsuario);
            }
            if ((this.onAlterarUsuarioCompletedDelegate == null)) {
                this.onAlterarUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAlterarUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginAlterarUsuarioDelegate, new object[] {
                        id,
                        nome,
                        referenciaDeAutenticacao}, this.onEndAlterarUsuarioDelegate, this.onAlterarUsuarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginAlterarSenha(string senha, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAlterarSenha(senha, referenciaDeAutenticacao, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndAlterarSenha(System.IAsyncResult result) {
            base.Channel.EndAlterarSenha(result);
        }
        
        private System.IAsyncResult OnBeginAlterarSenha(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string senha = ((string)(inValues[0]));
            System.Guid referenciaDeAutenticacao = ((System.Guid)(inValues[1]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginAlterarSenha(senha, referenciaDeAutenticacao, callback, asyncState);
        }
        
        private object[] OnEndAlterarSenha(System.IAsyncResult result) {
            ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndAlterarSenha(result);
            return null;
        }
        
        private void OnAlterarSenhaCompleted(object state) {
            if ((this.AlterarSenhaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AlterarSenhaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AlterarSenhaAsync(string senha, System.Guid referenciaDeAutenticacao) {
            this.AlterarSenhaAsync(senha, referenciaDeAutenticacao, null);
        }
        
        public void AlterarSenhaAsync(string senha, System.Guid referenciaDeAutenticacao, object userState) {
            if ((this.onBeginAlterarSenhaDelegate == null)) {
                this.onBeginAlterarSenhaDelegate = new BeginOperationDelegate(this.OnBeginAlterarSenha);
            }
            if ((this.onEndAlterarSenhaDelegate == null)) {
                this.onEndAlterarSenhaDelegate = new EndOperationDelegate(this.OnEndAlterarSenha);
            }
            if ((this.onAlterarSenhaCompletedDelegate == null)) {
                this.onAlterarSenhaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAlterarSenhaCompleted);
            }
            base.InvokeAsync(this.onBeginAlterarSenhaDelegate, new object[] {
                        senha,
                        referenciaDeAutenticacao}, this.onEndAlterarSenhaDelegate, this.onAlterarSenhaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginCriarUsuario(string nome, string login, string senha, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCriarUsuario(nome, login, senha, referenciaDeAutenticacao, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Marketplace.ServicoDeAutenticacao.Usuario Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndCriarUsuario(System.IAsyncResult result) {
            return base.Channel.EndCriarUsuario(result);
        }
        
        private System.IAsyncResult OnBeginCriarUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nome = ((string)(inValues[0]));
            string login = ((string)(inValues[1]));
            string senha = ((string)(inValues[2]));
            System.Guid referenciaDeAutenticacao = ((System.Guid)(inValues[3]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginCriarUsuario(nome, login, senha, referenciaDeAutenticacao, callback, asyncState);
        }
        
        private object[] OnEndCriarUsuario(System.IAsyncResult result) {
            Marketplace.ServicoDeAutenticacao.Usuario retVal = ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndCriarUsuario(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCriarUsuarioCompleted(object state) {
            if ((this.CriarUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CriarUsuarioCompleted(this, new CriarUsuarioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CriarUsuarioAsync(string nome, string login, string senha, System.Guid referenciaDeAutenticacao) {
            this.CriarUsuarioAsync(nome, login, senha, referenciaDeAutenticacao, null);
        }
        
        public void CriarUsuarioAsync(string nome, string login, string senha, System.Guid referenciaDeAutenticacao, object userState) {
            if ((this.onBeginCriarUsuarioDelegate == null)) {
                this.onBeginCriarUsuarioDelegate = new BeginOperationDelegate(this.OnBeginCriarUsuario);
            }
            if ((this.onEndCriarUsuarioDelegate == null)) {
                this.onEndCriarUsuarioDelegate = new EndOperationDelegate(this.OnEndCriarUsuario);
            }
            if ((this.onCriarUsuarioCompletedDelegate == null)) {
                this.onCriarUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCriarUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginCriarUsuarioDelegate, new object[] {
                        nome,
                        login,
                        senha,
                        referenciaDeAutenticacao}, this.onEndCriarUsuarioDelegate, this.onCriarUsuarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginBloquearUsuario(long id, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginBloquearUsuario(id, referenciaDeAutenticacao, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndBloquearUsuario(System.IAsyncResult result) {
            base.Channel.EndBloquearUsuario(result);
        }
        
        private System.IAsyncResult OnBeginBloquearUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            long id = ((long)(inValues[0]));
            System.Guid referenciaDeAutenticacao = ((System.Guid)(inValues[1]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginBloquearUsuario(id, referenciaDeAutenticacao, callback, asyncState);
        }
        
        private object[] OnEndBloquearUsuario(System.IAsyncResult result) {
            ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndBloquearUsuario(result);
            return null;
        }
        
        private void OnBloquearUsuarioCompleted(object state) {
            if ((this.BloquearUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BloquearUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void BloquearUsuarioAsync(long id, System.Guid referenciaDeAutenticacao) {
            this.BloquearUsuarioAsync(id, referenciaDeAutenticacao, null);
        }
        
        public void BloquearUsuarioAsync(long id, System.Guid referenciaDeAutenticacao, object userState) {
            if ((this.onBeginBloquearUsuarioDelegate == null)) {
                this.onBeginBloquearUsuarioDelegate = new BeginOperationDelegate(this.OnBeginBloquearUsuario);
            }
            if ((this.onEndBloquearUsuarioDelegate == null)) {
                this.onEndBloquearUsuarioDelegate = new EndOperationDelegate(this.OnEndBloquearUsuario);
            }
            if ((this.onBloquearUsuarioCompletedDelegate == null)) {
                this.onBloquearUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBloquearUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginBloquearUsuarioDelegate, new object[] {
                        id,
                        referenciaDeAutenticacao}, this.onEndBloquearUsuarioDelegate, this.onBloquearUsuarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.BeginObterIdDoUsuarioPorReferenciaDeAutenticacao(System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObterIdDoUsuarioPorReferenciaDeAutenticacao(referenciaDeAutenticacao, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        long Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao.EndObterIdDoUsuarioPorReferenciaDeAutenticacao(System.IAsyncResult result) {
            return base.Channel.EndObterIdDoUsuarioPorReferenciaDeAutenticacao(result);
        }
        
        private System.IAsyncResult OnBeginObterIdDoUsuarioPorReferenciaDeAutenticacao(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid referenciaDeAutenticacao = ((System.Guid)(inValues[0]));
            return ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).BeginObterIdDoUsuarioPorReferenciaDeAutenticacao(referenciaDeAutenticacao, callback, asyncState);
        }
        
        private object[] OnEndObterIdDoUsuarioPorReferenciaDeAutenticacao(System.IAsyncResult result) {
            long retVal = ((Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao)(this)).EndObterIdDoUsuarioPorReferenciaDeAutenticacao(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObterIdDoUsuarioPorReferenciaDeAutenticacaoCompleted(object state) {
            if ((this.ObterIdDoUsuarioPorReferenciaDeAutenticacaoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObterIdDoUsuarioPorReferenciaDeAutenticacaoCompleted(this, new ObterIdDoUsuarioPorReferenciaDeAutenticacaoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObterIdDoUsuarioPorReferenciaDeAutenticacaoAsync(System.Guid referenciaDeAutenticacao) {
            this.ObterIdDoUsuarioPorReferenciaDeAutenticacaoAsync(referenciaDeAutenticacao, null);
        }
        
        public void ObterIdDoUsuarioPorReferenciaDeAutenticacaoAsync(System.Guid referenciaDeAutenticacao, object userState) {
            if ((this.onBeginObterIdDoUsuarioPorReferenciaDeAutenticacaoDelegate == null)) {
                this.onBeginObterIdDoUsuarioPorReferenciaDeAutenticacaoDelegate = new BeginOperationDelegate(this.OnBeginObterIdDoUsuarioPorReferenciaDeAutenticacao);
            }
            if ((this.onEndObterIdDoUsuarioPorReferenciaDeAutenticacaoDelegate == null)) {
                this.onEndObterIdDoUsuarioPorReferenciaDeAutenticacaoDelegate = new EndOperationDelegate(this.OnEndObterIdDoUsuarioPorReferenciaDeAutenticacao);
            }
            if ((this.onObterIdDoUsuarioPorReferenciaDeAutenticacaoCompletedDelegate == null)) {
                this.onObterIdDoUsuarioPorReferenciaDeAutenticacaoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObterIdDoUsuarioPorReferenciaDeAutenticacaoCompleted);
            }
            base.InvokeAsync(this.onBeginObterIdDoUsuarioPorReferenciaDeAutenticacaoDelegate, new object[] {
                        referenciaDeAutenticacao}, this.onEndObterIdDoUsuarioPorReferenciaDeAutenticacaoDelegate, this.onObterIdDoUsuarioPorReferenciaDeAutenticacaoCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao CreateChannel() {
            return new ServicoDeAutenticacaoClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ServicoDeAutenticacao)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ServicoDeAutenticacao)) {
                return new System.ServiceModel.EndpointAddress("http://200.143.8.103/ENT_MKTv21.2Servicos/Seguranca/Servicos/ServicoDeAutenticaca" +
                        "o.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ServicoDeAutenticacaoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ServicoDeAutenticacao);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ServicoDeAutenticacaoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ServicoDeAutenticacao);
        }
        
        private class ServicoDeAutenticacaoClientChannel : ChannelBase<Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao>, Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao {
            
            public ServicoDeAutenticacaoClientChannel(System.ServiceModel.ClientBase<Marketplace.ServicoDeAutenticacao.ServicoDeAutenticacao> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAutenticar(string login, string senha, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = login;
                _args[1] = senha;
                System.IAsyncResult _result = base.BeginInvoke("Autenticar", _args, callback, asyncState);
                return _result;
            }
            
            public System.Guid EndAutenticar(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Guid _result = ((System.Guid)(base.EndInvoke("Autenticar", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAutenticarComOrigem(string login, string senha, string origem, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = login;
                _args[1] = senha;
                _args[2] = origem;
                System.IAsyncResult _result = base.BeginInvoke("AutenticarComOrigem", _args, callback, asyncState);
                return _result;
            }
            
            public System.Guid EndAutenticarComOrigem(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Guid _result = ((System.Guid)(base.EndInvoke("AutenticarComOrigem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginNotificaLimpezaDadosLocais(string login, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = login;
                System.IAsyncResult _result = base.BeginInvoke("NotificaLimpezaDadosLocais", _args, callback, asyncState);
                return _result;
            }
            
            public void EndNotificaLimpezaDadosLocais(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("NotificaLimpezaDadosLocais", _args, result);
            }
            
            public System.IAsyncResult BeginObterUrlVersao(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ObterUrlVersao", _args, callback, asyncState);
                return _result;
            }
            
            public string EndObterUrlVersao(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ObterUrlVersao", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginObterVersaoAndroid(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ObterVersaoAndroid", _args, callback, asyncState);
                return _result;
            }
            
            public string EndObterVersaoAndroid(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ObterVersaoAndroid", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListarParametrizacoes(System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = referenciaDeAutenticacao;
                System.IAsyncResult _result = base.BeginInvoke("ListarParametrizacoes", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Parametrizacao> EndListarParametrizacoes(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Parametrizacao> _result = ((System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Parametrizacao>)(base.EndInvoke("ListarParametrizacoes", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListarUsuarios(System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = referenciaDeAutenticacao;
                System.IAsyncResult _result = base.BeginInvoke("ListarUsuarios", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Usuario> EndListarUsuarios(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Usuario> _result = ((System.Collections.ObjectModel.ObservableCollection<Marketplace.ServicoDeAutenticacao.Usuario>)(base.EndInvoke("ListarUsuarios", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginObterUsuario(long id, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = id;
                _args[1] = referenciaDeAutenticacao;
                System.IAsyncResult _result = base.BeginInvoke("ObterUsuario", _args, callback, asyncState);
                return _result;
            }
            
            public Marketplace.ServicoDeAutenticacao.Usuario EndObterUsuario(System.IAsyncResult result) {
                object[] _args = new object[0];
                Marketplace.ServicoDeAutenticacao.Usuario _result = ((Marketplace.ServicoDeAutenticacao.Usuario)(base.EndInvoke("ObterUsuario", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAlterarUsuario(long id, string nome, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = id;
                _args[1] = nome;
                _args[2] = referenciaDeAutenticacao;
                System.IAsyncResult _result = base.BeginInvoke("AlterarUsuario", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAlterarUsuario(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AlterarUsuario", _args, result);
            }
            
            public System.IAsyncResult BeginAlterarSenha(string senha, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = senha;
                _args[1] = referenciaDeAutenticacao;
                System.IAsyncResult _result = base.BeginInvoke("AlterarSenha", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAlterarSenha(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AlterarSenha", _args, result);
            }
            
            public System.IAsyncResult BeginCriarUsuario(string nome, string login, string senha, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = nome;
                _args[1] = login;
                _args[2] = senha;
                _args[3] = referenciaDeAutenticacao;
                System.IAsyncResult _result = base.BeginInvoke("CriarUsuario", _args, callback, asyncState);
                return _result;
            }
            
            public Marketplace.ServicoDeAutenticacao.Usuario EndCriarUsuario(System.IAsyncResult result) {
                object[] _args = new object[0];
                Marketplace.ServicoDeAutenticacao.Usuario _result = ((Marketplace.ServicoDeAutenticacao.Usuario)(base.EndInvoke("CriarUsuario", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginBloquearUsuario(long id, System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = id;
                _args[1] = referenciaDeAutenticacao;
                System.IAsyncResult _result = base.BeginInvoke("BloquearUsuario", _args, callback, asyncState);
                return _result;
            }
            
            public void EndBloquearUsuario(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("BloquearUsuario", _args, result);
            }
            
            public System.IAsyncResult BeginObterIdDoUsuarioPorReferenciaDeAutenticacao(System.Guid referenciaDeAutenticacao, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = referenciaDeAutenticacao;
                System.IAsyncResult _result = base.BeginInvoke("ObterIdDoUsuarioPorReferenciaDeAutenticacao", _args, callback, asyncState);
                return _result;
            }
            
            public long EndObterIdDoUsuarioPorReferenciaDeAutenticacao(System.IAsyncResult result) {
                object[] _args = new object[0];
                long _result = ((long)(base.EndInvoke("ObterIdDoUsuarioPorReferenciaDeAutenticacao", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_ServicoDeAutenticacao,
        }
    }
}
